#!/bin/bash

echo "Enter Filename:"

read Filename

while read line; do amass enum -d $line -w /home/rouge/data/manual/2m-subdomains.txt -o amass1.txt; done < $Filename
while read line; do amass enum -d $line -o amass2.txt; done < $Filename
while read line; do assetfinder --subs-only $line | tee -a assetfinder.txt; done < $Filename
while read line; do subfinder -v -d $line -o subfinder.txt; done < $Filename
cat amass1.txt amass2.txt assetfinder.txt subfinder.txt | sort -u | tee -a All_Subdomains.txt
cat All_Subdomains.txt | httpx -p 80, 81, 300, 443, 591, 593, 832, 981, 1010, 1311, 2082, 2087, 2095, 2096, 2480, 3000, 3128, 3333, 4243, 4567, 4711, 4712, 4993, 5000, 5104, 5108, 5800, 6543, 7000, 7396, 7474, 8000, 8001, 8008, 8014, 8042, 8069, 8080, 8081, 8088, 8090, 8091, 8118, 8123, 8172, 8222, 8243, 8280, 8281, 8333, 8443, 8500, 8834, 8880, 8888, 8983, 9000, 9043, 9060, 9080, 9090, 9091, 9200, 9443, 9800, 9981, 12443, 16080, 18091, 18092, 20720, 28017 -o httpx.txt
cat All_Subdomains.txt | httpx -sc -td -server -title -location -o httpx2.txt
nuclei -t /home/ravi/nuclei-templates/ -l httpx.txt -o nuclei.txt
mkdir aquatone
cat httpx.txt | aquatone -ports xlarge -out aquatone/
cat httpx.txt | gau --subs --blacklist png,jpg,gif,jpeg,swf,woff,svg,css --o gau.txt
katana -list httpx.txt -jc -kf -aff -ef png,jpg,gif,jpeg,swf,woff,svg,css -o katana.txt
cat gau.txt katana.txt | sort -u | tee -a allUrls.txt | httpx -mc 200,403 -o LiveUrls.txt
nuclei -t /home/rouge/nuclei-templates/ -l LiveUrls.txt -es info -o nucleiAll.txt
echo "Recon is Done" | notify -silent
cat httpx.txt | for i in $(cat httpx.txt); do DOMAIN=$(echo $i | unfurl format %d); ffuf -u $i/FUZZ -w /home/rouge/data/manual/raft-large-directories.txt -fc 404 -recursion -r -o ${DOMAIN}_ffuf.txt; done
echo "FFUF is Done" | notify -silent
