#!/bin/bash

echo "Enter Filename:"

read Filename

while read line; do amass enum -d $line -w /home/root/data/manual/2m-subdomains.txt -o amass1.txt; done < $Filename
while read line; do amass enum -d $line -o amass2.txt; done < $Filename
while read line; do assetfinder --subs-only $line | tee -a assetfinder.txt; done < $Filename
while read line; do subfinder -v -all -d $line -o subfinder.txt; done < $Filename
while read line; do sublist3r -v -b -d $line -o sublist3r.txt; done < $Filename
cat amass1.txt amass2.txt assetfinder.txt subfinder.txt sublist3r.txt | sort -u | tee -a All_Subdomains.txt
cat All_Subdomains.txt | httpx -o httpx.txt
cat All_Subdomains.txt | httpx -sc -td -server -title -location -o httpx2.txt
nuclei -t /root/nuclei-templates/ -l httpx.txt -o nuclei.txt
gowitness file -f httpx.txt -p Gowitness/
